from django.core.management.base import BaseCommand
from main_app.models import BugWeather

spawn_weather_tuples = [
    ("agrias butterfly", "any except rain"),
    ("ant", "any"),
    ("Atlas moth", "any"),
    ("bagworm", "any"),
    ("banded dragonfly", "any except rain"),
    ("bell cricket", "any"),
    ("blue weevil beetle", "any"),
    ("brown cicada", "any"),
    ("centipede", "any"),
    ("cicada shell", "any"),
    ("citrus long-horned beetle", "any except rain"),
    ("common bluebottle", "any except rain"),
    ("common butterfly", "any except rain"),
    ("cricket", "any except rain"),
    ("cyclommatus stag", "any"),
    ("damselfly", "any except rain"),
    ("darner dragonfly", "any except rain"),
    ("diving beetle", "any"),
    ("drone beetle", "any"),
    ("dung beetle", "any"),
    ("earth-boring dung beetle", "any"),
    ("emperor butterfly", "any except rain"),
    ("evening cicada", "any"),
    ("firefly", "any except rain"),
    ("flea", "any"),
    ("fly", "any"),
    ("giant cicada", "any"),
    ("giant stag", "any"),
    ("giant water bug", "any"),
    ("Giraffe Stag", "any"),
    ("Golden Stag", "any"),
    ("Goliath Beetle", "any"),
    ("grasshopper", "any except rain"),
    ("great purple emperor", "any except rain"),
    ("hermit crab", "any"),
    ("honeybee", "any except rain"),
    ("horned atlas", "any"),
    ("horned dynastid", "any"),
    ("horned elephant", "any"),
    ("horned hercules", "any"),
    ("Jewel Beetle", "any except rain"),
    ("ladybug", "any except rain"),
    ("long locust", "any"),
    ("Madagascan sunset moth", "any except rain"),
    ("man-faced stink bug", "any except rain"),
    ("mantis", "any except rain"),
    ("migratory locust", "any"),
    ("Miyama Stag", "any"),
    ("mole cricket", "any"),
    ("monarch butterfly", "any except rain"),
    ("mosquito", "any except rain"),
    ("moth", "any except rain"),
    ("orchid mantis", "any except rain"),
    ("paper kite butterfly", "any except rain"),
    ("peacock butterfly", "any except rain"),
    ("Pill Bug", "any"),
    ("pondskater", "any"),
    ("Queen Alexandra's birdwing", "any except rain"),
    ("Rainbow Stag", "any"),
    ("Rajah Brooke's birdwing", "any except rain"),
    ("red dragonfly", "any except rain"),
    ("rice grasshopper", "any"),
    ("robust cicada", "any"),
    ("Rosalia Batesi Beetle", "any except rain"),
    ("Saw Stag", "any"),
    ("Scarab Beetle", "any"),
    ("scorpion", "any"),
    ("snail", "rain only"),
    ("spider", "any"),
    ("stinkbug", "any except rain"),
    ("tarantula", "any"),
    ("tiger beetle", "any except rain"),
    ("tiger butterfly", "any except rain"),
    ("Violin Beetle", "any except rain"),
    ("Walker cicada", "any"),
    ("walking leaf", "any"),
    ("walking stick", "any"),
    ("wasp", "any"),
    ("wharf roach", "any"),
    ("Yellow butterfly", "any except rain")
]

class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        self.stdout.write("Removing all rows from bug weather table via BugWeather.objects.all().delete()...")
        BugWeather.objects.all().delete()
        self.stdout.write("Seeding bug weather table by iterating BugWeather.objects.create()...")
        for spawn_weather_tuple in spawn_weather_tuples:
            BugWeather.objects.create(name = spawn_weather_tuple[0], spawn_weather = spawn_weather_tuple[1])
            self.stdout.write(f'Inserted "{spawn_weather_tuple[0]}" row with weather "{spawn_weather_tuple[1]}".')
        self.stdout.write("Finished seeding table.")