# Generated by Django 5.0.1 on 2024-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=256)),
                ('time_of_year', models.CharField(max_length=100)),
                ('south_hemi_toy', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('shadow_size', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('misc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fossils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
