# Generated by Django 5.0.1 on 2024-02-06 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='location',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='shadow_size',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='south_hemi_toy',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='time_of_day',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='time_of_year',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='value',
        ),
        migrations.RemoveField(
            model_name='fossils',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fossils',
            name='value',
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fossils',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
