# Generated by Django 5.0.2 on 2024-02-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spawn_weather', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='weather',
        ),
    ]
